---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:17.07.0-ce
    working_directory: /tmp/build
    environment:
      DOCKER_USERNAME: travisciresin
      DOCKER_EMAIL: accounts+travisci+docker@resin.io
      DOCKER_IMAGE: resin/docs
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker info
          env | sort
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: build
          command: |
            docker pull ${DOCKER_IMAGE}:latest || true
            docker build --rm=false --pull --tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} .
      - deploy:
          name: deploy
          command: |
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push ${DOCKER_IMAGE}:${CIRCLE_SHA1}
            docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker push ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:latest
            docker push ${DOCKER_IMAGE}:latest

            if [ "${CIRCLE_TAG}" != "" ]; then
              docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${CIRCLE_TAG}
              docker push ${DOCKER_IMAGE}:${CIRCLE_TAG}
            fi